// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: detection.proto
#ifndef GRPC_detection_2eproto__INCLUDED
#define GRPC_detection_2eproto__INCLUDED

#include "detection.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

// NEW PART:
//
// protobuf defines the DATA above.
//
// gRPC uses this service definition to define the RPC.
//
class RadarService final {
 public:
  static constexpr char const* service_full_name() {
    return "RadarService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SendDetection(::grpc::ClientContext* context, const ::Detection& request, ::DetectionReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::DetectionReply>> AsyncSendDetection(::grpc::ClientContext* context, const ::Detection& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::DetectionReply>>(AsyncSendDetectionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::DetectionReply>> PrepareAsyncSendDetection(::grpc::ClientContext* context, const ::Detection& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::DetectionReply>>(PrepareAsyncSendDetectionRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SendDetection(::grpc::ClientContext* context, const ::Detection* request, ::DetectionReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendDetection(::grpc::ClientContext* context, const ::Detection* request, ::DetectionReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::DetectionReply>* AsyncSendDetectionRaw(::grpc::ClientContext* context, const ::Detection& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::DetectionReply>* PrepareAsyncSendDetectionRaw(::grpc::ClientContext* context, const ::Detection& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendDetection(::grpc::ClientContext* context, const ::Detection& request, ::DetectionReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::DetectionReply>> AsyncSendDetection(::grpc::ClientContext* context, const ::Detection& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::DetectionReply>>(AsyncSendDetectionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::DetectionReply>> PrepareAsyncSendDetection(::grpc::ClientContext* context, const ::Detection& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::DetectionReply>>(PrepareAsyncSendDetectionRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendDetection(::grpc::ClientContext* context, const ::Detection* request, ::DetectionReply* response, std::function<void(::grpc::Status)>) override;
      void SendDetection(::grpc::ClientContext* context, const ::Detection* request, ::DetectionReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::DetectionReply>* AsyncSendDetectionRaw(::grpc::ClientContext* context, const ::Detection& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::DetectionReply>* PrepareAsyncSendDetectionRaw(::grpc::ClientContext* context, const ::Detection& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendDetection_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SendDetection(::grpc::ServerContext* context, const ::Detection* request, ::DetectionReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendDetection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendDetection() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendDetection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendDetection(::grpc::ServerContext* /*context*/, const ::Detection* /*request*/, ::DetectionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendDetection(::grpc::ServerContext* context, ::Detection* request, ::grpc::ServerAsyncResponseWriter< ::DetectionReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendDetection<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendDetection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendDetection() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Detection, ::DetectionReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Detection* request, ::DetectionReply* response) { return this->SendDetection(context, request, response); }));}
    void SetMessageAllocatorFor_SendDetection(
        ::grpc::MessageAllocator< ::Detection, ::DetectionReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Detection, ::DetectionReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendDetection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendDetection(::grpc::ServerContext* /*context*/, const ::Detection* /*request*/, ::DetectionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendDetection(
      ::grpc::CallbackServerContext* /*context*/, const ::Detection* /*request*/, ::DetectionReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendDetection<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendDetection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendDetection() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendDetection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendDetection(::grpc::ServerContext* /*context*/, const ::Detection* /*request*/, ::DetectionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendDetection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendDetection() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendDetection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendDetection(::grpc::ServerContext* /*context*/, const ::Detection* /*request*/, ::DetectionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendDetection(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendDetection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendDetection() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendDetection(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendDetection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendDetection(::grpc::ServerContext* /*context*/, const ::Detection* /*request*/, ::DetectionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendDetection(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendDetection : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendDetection() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Detection, ::DetectionReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Detection, ::DetectionReply>* streamer) {
                       return this->StreamedSendDetection(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendDetection() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendDetection(::grpc::ServerContext* /*context*/, const ::Detection* /*request*/, ::DetectionReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendDetection(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Detection,::DetectionReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendDetection<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendDetection<Service > StreamedService;
};


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_detection_2eproto__INCLUDED
