// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: detection.proto

#include "detection.pb.h"
#include "detection.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

static const char* RadarService_method_names[] = {
  "/RadarService/SendDetection",
};

std::unique_ptr< RadarService::Stub> RadarService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< RadarService::Stub> stub(new RadarService::Stub(channel, options));
  return stub;
}

RadarService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendDetection_(RadarService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status RadarService::Stub::SendDetection(::grpc::ClientContext* context, const ::Detection& request, ::DetectionReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Detection, ::DetectionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendDetection_, context, request, response);
}

void RadarService::Stub::async::SendDetection(::grpc::ClientContext* context, const ::Detection* request, ::DetectionReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Detection, ::DetectionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDetection_, context, request, response, std::move(f));
}

void RadarService::Stub::async::SendDetection(::grpc::ClientContext* context, const ::Detection* request, ::DetectionReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendDetection_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::DetectionReply>* RadarService::Stub::PrepareAsyncSendDetectionRaw(::grpc::ClientContext* context, const ::Detection& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::DetectionReply, ::Detection, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendDetection_, context, request);
}

::grpc::ClientAsyncResponseReader< ::DetectionReply>* RadarService::Stub::AsyncSendDetectionRaw(::grpc::ClientContext* context, const ::Detection& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendDetectionRaw(context, request, cq);
  result->StartCall();
  return result;
}

RadarService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      RadarService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< RadarService::Service, ::Detection, ::DetectionReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](RadarService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Detection* req,
             ::DetectionReply* resp) {
               return service->SendDetection(ctx, req, resp);
             }, this)));
}

RadarService::Service::~Service() {
}

::grpc::Status RadarService::Service::SendDetection(::grpc::ServerContext* context, const ::Detection* request, ::DetectionReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


